blank_issues_enabled: false
contact_links:
  - name: "💬 Questions & Support"
    url: https://github.com/UserAAR/FinancAAR-Mobile/discussions
    about: "Please use GitHub Discussions for questions that are not bugs or feature requests." 