#!/usr/bin/env bash
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
echo dummy shell
